---
title: '夏天之二'
author: "Midstream"
date: '2023-04-22'
categories: ['小说']
description: 直至今日，我依然觉得这是我生命中最灿烂的一个下午，我们在黄金的光辉中喝得烂醉，呓语着过去和将来。

---

时隔多年再次踏上硬卧车箱的时候，我诧异于那来自灵魂深处的自在，仿若十多年前的那个世界还依然年轻，蓬勃着不需要缅怀。我贪婪地嗅着尘螨和人的味道，车窗外的一切向深处隐退。

16岁那年，我也是乘着这样的一列火车，离开父母而奔向南方。临别时我曾告诉我的兄弟们，以后南方是我的地盘了，有空来玩，我罩着。我曾如此坚信我终将闯出一番天地，狂妄得让人嫉妒。

我其实并不是一个有斗志的人，否则也不会初二辍学后开始混迹市井。父亲后来听说我小叔在南方开了一家洗车店，便让我去帮工了，也算有个工作。于是，我明白我的未来在南方。

我昂扬地走进那个夏天。

### 1

我曾以为南方就是海边，有车水马龙，有彩灯和舞厅。直到我住下几个礼拜之后我才明白，我所在的南方并没有海。

我住在洗车店后侧的平房里。南方雨水多，平房地势低洼，雨大的时候我的铁床下会蓄起一层水，灰尘、烟头、头发、还有虫豸的尸体，在水面上聚集成许多小小的岛屿。

洗车的活计很简单，也很枯燥。下班后我去网吧上网，有时就睡在网吧里，白天清闲时我常溜去隔壁报亭翻看杂志，一来二去通过杂志迷恋上了汽车。从那以后我便不再觉得洗车无趣了，触碰车的时候我总觉得它们有自己的灵魂，我日思夜想着能拥有一辆自己的汽车。

我跟小叔说，我要学开车，小叔说那要等到你18岁。算起来还要一年半，太漫长了，我求小叔提前教我一点，他拒绝了。可是，身在洗车店的我有太多碰车的机会了，攒了几日的网费后，我用一盒20块的硬遵义说服了负责挪车的大哥。他坐在副驾，左手握着手刹，右手把玩着一个塑料打火机，看着我踩着离合将车滑进洗车房。初次碰车后，我愈发渴望驾驶了，像是沾染了毒品，这使得我不得不继续巴结挪车的大哥。停车的后院到洗车房之间的一百米，成为了我睡梦中都在驾驶的路段。

我认为我有相当的开车天赋，大哥也承认我学得很快。在我递给大哥第三包香烟的时候，我已经可以熟练地切换挡位，在我短短的赛道上踩一脚油门。大哥嘴里总说着慢点慢点，却不再将手放在手刹上了。再后来，每当需要挪车的时候我就会自觉地拿上钥匙，开车往返在这一百米的小路上。大哥乐得清闲，小叔也不常在店里。我一直怀疑小叔早都知晓了一切，不过睁一只眼闭一只眼，但他从来没跟我提过，我也不好直接问他。

洗车店的薪资不高，我也并不攒钱，可我总觉得我的车就在某处等着我。我筹划着想要买一辆斯巴鲁，或者大众高尔夫。

我在洗车店也没什么朋友，洗车店之外也就只有报刊的老板和我算是相熟。我知道小叔在工作安排上一直对我有关照，但我们很少有机会说话，而且，也没有话题。偶尔夜深之时，我躺在湿漉漉的硬板床上会想起父母还有以前的兄弟们，感觉仿佛是很遥远的回忆。

南方的夏天很长。我仿佛已经在南方生活了许久，可依然还没走出夏天，当我猛然意识到隔壁的学校不再播放铃声，我才发觉如今是暑假的时间——夏天竟然才过去一半，我竟然依旧是南方的新客。

### 2

我反复提醒自己，现在已经是疫情后的时代了，可我依然难以摆脱那股对旧时光的熟稔。我没有钻进我狭小的中铺，而是倚在窗边，手机放在那狭窄不过一掌的小桌子上。

缺一桶泡面。

我也不知道为何就这样在一个周末鬼使神差跳上了去往海边的火车，她应早就离开了那座城市才对，就算她依然存在，我也无力大海里捞针，但我依然觉得这班列车载着我在奔向她，奔向依然年轻的她。我始终难以将她与中年的颓败联系在一起。

她正是在那个夏天撞入我的生活的。

她叫陈妙，是我初中的同学。我初中少有出勤，和同学其实相当生疏。陈妙生的张扬，高个子，高鼻梁，是我一入学就注意到的女孩儿，这才没有在我的印象里和别的脸庞混为一谈。当时我认识陈妙更多是因为我有一个校外的哥们儿，老庄，曾狂热地追求过她。老庄比我大两岁，有些胖，个子也不高，我觉得老庄配不上陈妙。我不清楚他们之间具体是什么关系，但我辍学后仍偶尔能在烧烤摊偶遇他们。我和朋友很乐于调侃他们，换来老庄的大笑和陈妙的白眼。

在我动身去往南方之前，朋友们请我吃了一顿烤鱼，算作送行，老庄喊上了陈妙。那是我之前仅有的一次和她坐在同一桌吃饭，甚至整场饭局我们也没有说过话，因此当我收到陈妙的短信的时候我才感到如此不真切。

皓哥，这是短信的开头。没人称过我皓哥，熟络的朋友均呼我为“耗子”。

不知你在南方可好，你曾说有空去南方玩，有你罩着。我已在火车上，明早八点抵达，方便的话可以小聚叙旧。落款是陈妙。

我不曾有过陈妙的号码，也未曾想过一句客套话竟真的有人当真，更不知道我和她有何旧可叙。但对于当时孤寂的年轻的我来说，一位从北方来的客人却是意外的惊喜，更何况，她长得漂亮。我当然也察觉出这趟拜访的奇怪，想打电话问一下老庄，可我并不清楚她和老庄究竟是何关系，又怕不妥，便决定先接上陈妙，再直接问她。

我回复：很高兴你能来，明早我去车站接你。

我向小叔请了一天的假。当晚，我躺在床上看着头顶旋转的风扇，遗憾自己并没有地主的气派可以风光待客。或许就是从那一刻，我才逐渐真正认识到自己的破落的。

次日清晨，我动身前对着镜子认真地看了一眼自己，衬衫仔裤还算板正，只是头发有些潦草，身形也有些枯槁。

我在车站的出站口接到了陈妙，她戴着一顶白色的鸭舌帽，拖着一只小行李箱，在黑而短小的人群中格外显眼。我问陈妙为什么想到来我这里了，她说先不谈这个。我并没有料到这种答复，一时间不知道说什么。带我在南方转转吧，她说。我赶忙答应。

找了家旅社落宿后，我们去吃早餐，在洗车房隔壁我常去的早餐铺子。而后我带她在周围闲逛，添油加醋地叙述着我这段日子的生活，以及我的驾驶天赋。陈妙是惹眼的，领着她在路上时能感受到旁人的侧目。这让我骄傲。洗车房的伙计们冲我们吹口哨，对我挤眉弄眼，一如我曾经对老庄。

那天我的话格外多，等我反应过来时，我们已经绕了一大圈回到陈妙的旅社。我看了看表，过了午饭的时间了，但离晚饭还尚早。数了数兜里的钱，我跟陈妙说要不我请你去喝酒，我知道有家啤酒吧下午营业。陈妙说好。于是我们又转场去啤酒吧。说是啤酒吧，其实不过是个棚户，晚间还经营些烧烤，临街的路边也支了许多塑料桌椅，是我们最熟悉的形式。

那天的阳光格外明朗。在陈妙的坚持下，我们坐到了室外。在这个工作日的下午，我们是金灿灿的太阳下的唯二之人。我不知道我究竟喝了多少啤酒，只记得空瓶堆满在桌脚边。

我告诉陈妙，有一天我要买一辆自己的车，然后去很远很远的地方。

“什么地方？”她问。

“不重要”，我说，“只要是我开着自己的车就可以。”

“那你就没有想去的地方？”

“没有。”我摇头。

陈妙说她想去海边，南方的海边，所以第一站就先到我这里了。她也不知道要去往哪里的海边，哪里都可以，只要是海边，她说。

她又问我会不会一直住在南方，我说我不知道，但我偶尔会想回家。她问为什么，我说想找人说话。找人说话？对，我说，就像现在一样。我说我很感谢你能来，她笑，说不客气。

“可是你为什么会有我的手机号？”我问。

“找老庄要的。”

“那你为什么一个人来？老庄呢？”

“我去哪里关他什么事？”陈妙说。

“我以为你们......走得很近。”

陈妙笑了，明媚的阳光洒在她的脸上。“那你以为我和老庄什么关系？”

“我不知道。”

陈妙笑盈盈的脸凑近过来，“你们男人真搞笑。”

“那你们就是没关系咯？”我说。

“没——关——系——”她对我翻白眼。

直至今日，我依然觉得这是我生命中最灿烂的一个下午，我们在黄金的光辉中喝得烂醉，呓语着过去和将来。

### 3

我在颈椎的酸痛中醒来时，正靠坐在旅店房间的墙角。我艰难地扶墙起身，感受到口干舌燥还有半边身体的麻木。我看了看时间，尚是凌晨。我想起，我们是沐浴着晚霞回到旅店的，至于我为什么睡着在墙角，我却回忆不起。房间的灯开着，陈妙躺在床上，穿着外衣，还在睡。

看着她在灯光下熟睡的侧脸，我有些迟疑是否需要叫醒陈妙。我看到她脸颊上些许剥落的粉，方才反应过来她是带妆来见我的。再仔细看去，我才发现她的眼皮上有着色的痕迹，在室外一整天之后颜色变得斑驳，显得有点脏脏的。我不知道我这样盯着她看了多久，直到我发现她的眼皮开始跳动的时候我才猛然回过神，立刻移开目光。

我感到饥饿——上一顿还是早饭。我说我下楼去前台买两碗泡面。等我拿着泡面回到房间时，我发现她应该已经简单洗漱过，脸上不再有斑驳的痕迹了。

我们在窄小的桌子上吃泡面。她问我明天什么安排，我说我明天还没有请假，可能要回洗车房工作。我问她明天打算做什么，她说明天就动身去海边。哪里的海边？哪里都可以。下午的问答似乎又重复了一遍。

“所以，你来找我是因为你要先到南方，再去海边，是吗？”想到天亮后就要再回到我乏善可陈的日子，我有些患得患失。

“北方的海是冷的，黑的。”她说。“冷风不停从海里吹出来。”

我不知道，我没有见过大海，无论是南方还是北方。

“那你知道怎么走吗，去海边？”我问。

“往东边去。”她说。

“怎么去？还是乘火车吗？”

“不知道。”她说，“也可能坐巴士吧。”

泡面吃完了，我似乎也没有再继续留在这里的理由了，更何况我明早还要工作，我要回到我蜗居的平房里去。

“那你一路顺风！”我说，“等你到了海边，记得call我，报个平安。”

她冲我点头。

凌晨是没有公交车的，我只能徒步回洗车店。我走在路上，总觉得自己仿若走在海边，我能嗅到风里的咸咸的气息，树叶发出浪涌般的声响。这是我走过的最轻巧的一段夜路，仿若走在天上。

那熟悉的停车场出现在我的视线里的时候，一股失重感缭绕着我，像是从一个迷幻的梦境里坠落。我才反应过来，陈妙，海边，那不知道是哪里的城市，还有她的一切的迷人的未知，都与我无关了。我又要回那永远不会结束的夏天里，蹲在洗车房门口抽红塔山，往返于网吧和报亭，抚摸着别人的方向盘做白日梦。

我头一次对自己的生活产生过质疑。我想起陈妙问我会不会一直住在南方，我说我不知道。我又想起她问我有没有想去的地方，我说没有。

不知为什么我又想起老庄，那个矮胖子。我和当初市井上的朋友们都不是传统意义上的好学生，当然，陈妙定然也不是，可是老庄却是我们之中最“坏”的一个。他进过少管所，还给我们展示过他肚皮上蜈蚣一样的伤疤。我不懂为何陈妙总和老庄一起出现，虽然我辍学了，但我大约知道陈妙还一直在念书。

东方的天边泛起色彩了，停车场的一辆辆汽车的顶反射出光芒。或许还有一个小时，我就要拎起橡皮水管冲洗脚下的水泥台面了，彼时，陈妙也应重新画好妆，带上帽子，然后奔向海边。

梦，醒了。

我突然想到一种可能，它迅速扩张并占据了我的全部的念头——我也要去海边。

我跑进洗车房的办公室——我知道门上那颗小锁的密码。我在墙上的挂着的一张表格里搜索着，寻找着最晚的取车日期——为了方便管理车位，在店里过夜的汽车需要写上取车的日期。我很快锁定了目标，一辆标志206，三天后取车。我到盒子里拿了钥匙，到后院找到了这台灰突突的小车——应是昨晚送来的，还没来得及清洗。

我不知道去海边要多久，一天，还是三天，亦或者更久，但当我感受着顺着方向盘传来的引擎的抖动的时候，我知道，这是我必将踏上的旅程，和陈妙一同。

我开着标志206沿着我来时步行的路线回旅店，我又闻到了咸湿的海，我又冲进了那个差点离我远去的梦境。我在旅店接到了陈妙，我说我借到了车，我开车送你去海边。那一刻我感到自己无比的生气勃勃。

陈妙坐在我的副驾，我左手扶着方向盘，右手在挡杆上推拉横移。她问我知道怎么走吗？我说，你不是说东边就是大海吗，那就往东边走。我踩下油门，灰头土脸的标志206奔向初升的红日。原来，太阳从海上升起。

### 4

应该是有通知，我的手机屏幕亮了起来，我看到了锁屏界面的时间，还有半程。我拿起手机，前往盥洗室。我不想关心手机的通知是从哪里来的，或许是垃圾短信，或许是什么软件的推送，也或许是公司的办公群。我在盥洗室里洗脸，对着局促的小镜子审视自己的仪容，一如我去车站接陈妙的那个早上。可我现在早已失去了当初的昂扬，带上了眼镜，头顶稀疏。我曾经干瘦的躯体也已堆起了赘肉，只有倔强的四肢显出畸形的匀称。回到车厢，我看到窗外的绿色的丘陵，我知道，十多年前，一辆风尘仆仆的206曾从中穿行过。

我并不知道从那连绵的矮山中穿过的是国道还是省道抑或是无名的乡间路，但那却是我第一次开车进山。山里的驾驶乐趣远超平原，每次换挡，每一脚刹车，都会影响到汽车出弯的角度和线路，继而又会影响到下一次入弯，我兴奋地寻找着和山路的共鸣。在将要越过一个小山坡的顶端之时，我看到云烟里山脚下的城镇，那现在想来很是普通的景色却让我莫名地激动。我把车停靠到路边呼唤陈妙的时候却才发现，她已经侧靠在座椅上睡着了。

她问我怎么了。我说，看外面，好漂亮。她坐直起身看向窗外，脸侧有一块儿红红的、汽车头枕纹路的印子。我笑了，她不知道我为什么笑。

或许是我们选择的路线不对，或者海边真的很远，那天我们没能开到海边。日落的时候我们在一条乡间的小路上，两只倒车镜里是火红的天。日落的很快，没有路灯的道路变得漆黑。我们停在漫天繁星下，爬上车顶吃在加油站买的零食。

我看到一道白色的星痕快速划过然后消失。我说，我好像看到流星了。陈妙说，快许愿，然后虔诚地合拢双手，微闭上双眼。我看着星空，却不知道该许什么愿，突然的，我好像也不是那么想要买一辆车了。我说，迷信。陈妙像是没听到，依然合十着双手。她应该许了一个很长的愿望，我想。

夜深了以后气温降得很快，穿着夏装的我们只能回到车里。车窗上满满的一层水雾，像是拉了窗帘。那晚，陈妙告诉我她母亲在她小时候就去世了，父亲施暴倾向很严重，前几日她和父亲大吵一架后就离家出走了。

“然后你就来我这里了？”我问。

“是的，我想找一个南方海边的城市生活，想起你正好在南方混，就去找你了。”

“没想到我混得这么差是吧。”

“不啊，我觉得你过得挺好的，连车都有了。”

“借的车，要还的。”我苦笑。

“那你...还上学吗？”我问。

“之前在念高中，不过之后应该不会继续念书了。”她说，“念也念不会，继续读书也是浪费时间。”

“那等你到了以后，打算做什么工作？”

“反正就那几样吧，服务员，收银员，柜台什么的。养活自己肯定没问题。”

我们都把座椅放倒了，躺在座位上，我看着她，她看着车顶。

“你从家里出来以后，没去找老庄他们？”

“你怎么成天就知道老庄？”陈妙转过头来看向我。

“就，毕竟你之前和他来往比较多嘛，”我变化着措辞，“在你来南方之前其实我们也不算太内个。”

“嗯？那你想要怎么样？”

陈妙翻过身，一手撑到驾驶侧的车门上，逼近向我。她看向我的眼睛，呼吸喷在我的脸上，我感到年轻的热血往脑袋和下身涌去。我本想举起双手做投降状，最终却是直接吻上她，把她揽进怀里。

那之后，即使我再想起老庄，也不好意思提及了。

寻海之路的后半程就略显枯燥了，我们找上了一条新修建的高速，空荡无车且尚未收费，一路向东。途中遇到一次警察做出停车手势，让我惊惶万分，但最终发现他拦下的是我的后车，算是虚惊一场。

我们最终在第二天晚到了海边。我们下车踩到沙滩上，身前是涌动的海，身后是城市的灯光。我知道，已经来不及在明早把车泊回停车场了。我打算赶夜路回去，能早一点是一点，陈妙劝我留宿一夜明早再出发，我想了想还是拒绝了。我们在海边亲吻，道别。

我坐回车上，感到自己正逐渐从梦幻中醒来。我按了按手机，早就没电关机了，但或许也是好事。盗车的惶恐逐渐淹没上来，我得回去了。

### 5

我被人群推挤着下车，又被人群推挤着离开火车站。我到海边的城市了，但我什么感觉都没有。我确实也不应该有什么感觉，我上一次到访这座城市的时候还坐在一辆不属于我的标志206里，且只逗留了几个钟头。于我而言，这就是一个完全陌生的城市。

我到海边去等天黑。

我在一块沙滩上坐下，想起过去的十几年。离开洗车店后，我在南北之间辗转，开过小店，当过黄牛，倒卖过盗版影碟；也点过公主，谈过恋爱，相过亲。没结婚，不是不想，是没钱买房。在那个夏天过后的几个月内，我时而和陈妙还有短信的联系，我得知她在一家酒店当迎宾小姐。再后来，不知在哪一次换手机的时候，我弄丢了她的号码。后来，我也曾拥有过自己的汽车，一辆日产，疫情期间被我卖掉了。

我回忆这些过去的日子，总觉得像是在看别人的故事，我人生的上一幕似乎还停留在和陈妙分别的那个夜晚。

电话响了好几次，是领导的，都被我挂断了。我现在在一家房产中介工作，每日衬衫打领带，拿着比环卫工还低的工资。可就算是这样的一份工作，我依然珍视它，我没有挑剔的资本。

我无比羡慕曾经的自己，一无所有以至于一无所惧，跳上一辆不属于自己的车就开往未知的城市。现在我依然一穷二白，但却满身都是牵绊：手机另一头是我的老板，我的房东，我的保险，我投资的溃败的基金，需要我随叫随到的客户，以及我需要巴结的“朋友”。我到了海边，可我一直都没有离开。我想把手机扔进海里，像曾经的陈妙一样在这座海边的城市重新开始新的生活，但我知道我做不到。

天黑了，我踩在沙滩上，身前是涌动的海，身后是城市的灯光。

海边不再有陈妙。
