---
title: '几个人在说话'
author: "Midstream"
date: '2021-08-07'
categories: ['抽象艺术']
description: A：我们来说话吧。B：好。
---
A：我们来说话吧。


B：好。


C：可以，我们来说话吧。


B：那要找点什么说，对吧。


C：正经地说一次话确实需要话题。


A：要不，说点平常不会说的？


B：平常不会说的？那我现在也不会说，将来也不会说的，至少对你们不会说，比如我的性癖。


A：这倒是个不错的话题，至少在正经的对话里不会出现。


B：不正经的对话里倒是很常见（笑


C：说得好，为什么在正经的对话里不怎么出现性？


A：你问这个问题就好像在问为什么不能把粑粑拉在星巴克的桌子上。为什么人会羞耻，为什么会有道德观？毕竟法律也没有规定你不能在说话的时候提起你的性癖。


B:
人总是很矛盾，一边倡导着说应该正视性这种欲望，对待它就要像对待吃饭喝水一样，一边又暗自认为其肮脏而污秽于是需要在“干净的场合“避开。（用双手在脑袋两边比划了一对引号）


C：好歹是七宗罪之一，哪这么容易就平反。


B：不过但丁把这玩意儿排在老末怕是有些屈才了，要是有新七宗罪我觉得前三甲还是有点希望的。


A：这么说你是“保守党”的？（学着B比划引号）


B：可以这么说？我觉得性多多少少和污秽沾得比较多。


C：除了一个爱，剩下能联系到的都不是很好。


B：粗俗与凌乱，统治与暴力，占有，自私，反常与变态。自然法则本来就是毫无公平、善恶可言，残忍而暴虐的，演化之所以将快感赋予了性，是因为性是物种在自然法则下延续的最重要的一环。甚至你说的爱在最初都和性并不沾边，演化里的性的快感是不能长久的，是淡漠而凉薄而利己的，有着控制生物的能力。至于爱情，我觉得这是社会的产物，至少是智慧群体的产物。


A：确实，性吸引把生物聚到一起，然后惨烈的斗争，胜者为王，然后拔吊无情，甚至屠杀别人的后代。


B：或许性本身并不是堕落的，罪魁祸首应该是性吸引，七宗罪里没有性而是色欲应该也是这个道理。不对，其实应该说，罪魁祸首应该是自然法则，弱肉强食的世界，没有正义和善良可言，所以人最贴近自然的欲望都最强烈，而且最肮脏。越原始，越堕落，大自然不是母亲，而是万恶之源头。不过现代社会让大部分的原始的欲望都被限制了，性又ban不掉，就显得格外污秽。其实不是性污秽，而是它贴近生物的本能，凭本能做事，谁都十恶不赦。


A：占有欲，支配欲，控制欲，征服欲，破坏欲……妥妥一个现代社会啊。


B：现代社会也被自然法则控制着，但是好歹我们在人类社会能发现真正的善和美，并且不用直面血淋淋的自然。


A：啧啧啧，不用直面血淋淋的自然，而是隔了假惺惺的面具，不能杀人，但能诛心。


B：我们好歹可以抗争，人类作为一种生物，自然的原始的恶是存在于身体血脉里的，但是人作为万物之灵也有神性存在于精神里，残虐会让人心痛，破碎会让人惋惜。人可以有意识地压制这些原始的欲望，逐渐脱离野蛮，触及自己内心的神性，有点儿像出家人通过禁欲的方式来摆脱世间污秽，达到超脱。


A：懂，性盛致灾，割以永治。如果你割掉了小兄弟，理论上来说你的雄性激素的减少就会让你逐渐丧失那些世俗的欲望，然后你的爱就是纯粹的爱了，而且你也不会精虫上脑乱搞一通然后事后后悔了。嗯，我没有讽刺你。（认真脸）


C：差不多。按照他的说法，越接近自然，越底层越原始越缺乏理性，这些欲望被满足带来的快感越强烈越短暂越，也越容易让人空虚，让人后悔，也越容易死灰复燃；反之越高层越文明越理性，快感越平和越恒久越让人满足。


C：不过，既然你相信进化论，那之前说的那些“神性”，应该也是自然创生的才对，或者换句话说，人为什么会有同情、慈悲、怜悯？人有破坏欲，想打碎完整的瓷瓶，但人也有保护欲，不愿瓷瓶被打破。这些光辉的神性或许和堕落的兽性同源呢，那如果这样说，自然真的是原罪吗？


B：这个瓷瓶的比喻非常nice，对应你说的两种快感。我确实相信进化论，但是被赞美的美德绝大多数都是人类所独有的。而且其实我对进化论也不是那么迷信，毕竟七万年前那场认知革命看起来确实有如神之手点化一样。我的唯物其实不太坚定。（笑）


A：美德之所以为美德还不是人类社会定义的。大自然不是恶堕的，当然，也不是善良的。何为善，何为恶？万物利己，天经地义。人捏造出善恶之分也是为了更大程度上维护自己的那点可笑的利益罢了，让别人不要侵害自己的利益，最好能做一些有益于自己的事儿。干嘛非要分什么善恶嘞，本来这个世界上就没有善恶。人不为己，天诛地灭。


B：我知道你不是这个意思，但是听起来像是在鼓励人犯法。


A：其实就是遵从内心的欲望罢了，懦弱卑微，欺软怕硬不也是生物的本能吗？真正利己的人肯定害怕法律的惩罚。而且，这也甚至不是鼓励人钻法律漏洞，因为一个人如果有点道德，或许内疚感的权重会更大，那么这个利己者就会选择一些更合乎情理的方式来或许利益，君子爱财取之有道嘛，这才是道德该发挥作用的地方，社会自然而然会把利他的行为推举为道德模范。


C：按照这个逻辑走下去，人想要不利己都不行了。


A：差不多吧，人在无时无刻不做出决定，但是人永远会选择在那一瞬间有利于自己的，你为他人做出牺牲，在那一瞬间，肯定做出牺牲达到的东西权重要大于你的牺牲，因此你选择了利己的那一个，哪怕你故意做出有害于自己的事情，其实于你而言，打破这条规律的快感的权重要大于损害自己的损失，所以你还是选择了利己的那个。你选择了，但是也没有选择，因为你永远只会选利己更多的那个。


B：你这搞下去都成机械决定论了，海森堡要比我先不干了。人的确无时无刻不在选择，人就算每次选择必定利己，但是未来是不确定的，人的选择只能当下利己而不能永远正确，所以人会后悔。


A：人确实是个很喜欢后悔的物种，很多时候其实你选了你后悔的那一项你还是会后悔，因为现在正在发生的不快总是更不快一些。


B：所以你刚才说半天等于没说啊，人之为人，终究还是要受到自己的这具身体与底层的兽性的束缚。自然是无性的，确实，但是人是无法挣脱来自底层的念头的。你哪怕知道所谓善恶观念终究是演化，是空，但你依然无法摆脱世俗的欲望，哪怕出家人通过禁欲能摆脱世间的肮脏，却也要留下甚至扩大慈悲和怜悯。摆脱了肮脏，只剩悲悯，这是佛的视角吗？或许，但绝对不是自然的视角，人永远也无法达到自然的视角。你自以为超脱了，只不过是为了给自己一个享受低级快感的借口，而这最终只会给你空虚。按照你的利己理论，我觉得只求满足肉体兽性欲望而不求提升自己，这种利己，终究没有脱离肮脏的平和有分量。


A：说得好。但是我选择当一个俗人，我还是个处，让我体验七宗罪吧，我还不想出家。（笑）


C：不会真的有人聊着聊着就要出家了吧。（笑）


B：这倒不至于，但我可以当活雷锋。（笑）