---
title: 在这片土地上
author: "Midstream"
date: '2021-06-18'
categories: ['抽象艺术','日常','游记']
description: 我迫切的想打破沉默。但我又不敢喧哗，害怕打破这片土地的沉默。

---

<script language="JavaScript">
  //set password
  //防君子不防小人，如果你看到了这句话，请认真阅读，你会知道我为什么设置密码的
    function password() {
        var testV = 1;
        var pass1 = prompt('for some reasons, this blog need password to access:', '');

        if (pass1 != "233333"){
            if(history.length>1){
                history.go(-1);
            }else{
                window.location.href="https://midstream.cn"
            }
        }
        return "";
    }
    document.write(password());
</script>

##### 说在前面

亲爱的家人、朋友：

如果你能看到这些话，说明我对您有着百分百的信任。（当然，有些人我也十分信任，但是因为一些特殊原因我不能分享）

这里，我记录了我支教的见闻，为了避免学生隐私的泄露以及一些敏感话题引起的讨论，我只能向极小的一部分人公布这些文字，希望您不要传播，哪怕是出于善意。

文章中出现的人物和事件中95%都是我真实的所见所闻，剩下的5%是我的推测。我没有提及任何的名字，有些出现的姓氏也是经过更改的。关于孩子们的故事，我进行了打乱重组，一个人的事情我可能会拆开到两个人身上，几个人的事情我可能会结合到一个人身上。尽管如此，如果被知情人看到还是很容易确定当事人的身份，所以请大家不要传播。

我记录这些的时候没有想着要反应些什么，只是太多沉重的感触让我想倾诉，本文没有任何的立场。

如果您打算看这些文字的话，希望能认真而客观地对待这些事情。

最后，欢迎讨论，但是仅限私下，最好当面。

<br/><br/><br/><br/>



##### 正文：

<center>
这片土地上滴过汗

这片土地上溅过血

这片土地上荡漾过欢笑

这片土地上划落过泪水

这片土地上扬起过烟尘

这片土地上闪耀过星光

这片土地不安眠

这片土地不说话
</center>
<br/>



## 关于汗

#### 1.

“教育部发布防溺水致家长一封信，尊敬的中小学生家长朋友，溺水是造成中小学身边意外死亡的第一杀手。春季以后，天气逐渐变热，溺水又将进入高发季，希望广大家长务必……”

“牛马吧，让不让人睡觉了！”他把头探出窗户，用力地把眼睛挤成一条缝，只见明晃晃的一片，没有人，喇叭的广播声在三十三层的住宅楼之间来回反弹。他把窗户用力地关紧，隔绝了正午的炙热和喇叭声，然后松手，窗户往回弹开一条小缝，喇叭声又漏进来，在空荡荡的客厅里反弹。他回头看了一眼，再关紧，顿了一下，松手，窗户又弹开一个小缝，他没再说什么，踩着地板上的瓜子壳离开了窗前。

河水涨起来了，吹起了河床上泥土的水流不再比平日的清澈而是浑浊的淡绿色。校长站在河边，汗珠爬进他眼角深深的皱纹再爬出来，滴落在渡口盖了一层尘土的水泥地上，又很快在烈日下干涸，留下一个个淡淡的印迹，喇叭的广播是他放的。这是每周例行的巡河，在一天最热的四个小时里守在河畔，防止学生下河。四个小时过去了，他像个桩子一样杵在那，什么都没有看到，除了几只贪图他脚下阴影的苍蝇在绕啊绕。河很长，穿过整个城市，他只能守得住一个百步长的小河滩，百步之外，河流拐弯进了山里，喇叭声也被挡在这个拐弯的外面，谁也不知道那里有没有玩水的孩子。这个小河滩，他已经守了两年。他说，他曾经遇到过下河的孩子，把他们赶走了。



#### 2.
烈日下会在外面走动的，还有一个捡垃圾的老太太。她很矮，铁皮的垃圾桶很高，她每次把身体探进去都要用力踮起脚尖，把自己挂在垃圾桶的桶壁上。她的背很佝偻，可能再过两年，她就够不到桶深处的垃圾了。垃圾是卖给安置区外面的一个中年人的，他有一个小院子，里面都是打包好的从附近的安置区里收来的箱子和瓶子，每周三下午他会开一辆皮卡过来把这些垃圾运走。

老太太每天靠捡垃圾能赚十几块钱。她和她的孙子住在二号安置区C2-13-1-1户，是个60平米的中套。他们从沿河被精准扶贫搬迁来的时候，一家三口按照一人20平米的政策分到了这套房子，儿媳是儿子在广东打工的时候遇到的，生了孩子以后跟着丈夫回了沿河，当时还没有搬迁，家里是土房子，只勉强有电，儿媳受不了，没过多久就失踪了。后来因为政策搬迁了，她儿子也找了新工作，每个月能赚两千多，在这安置区里不算富有也不算穷苦。再后来，儿子在市里面喝多了捅了人，判了十几年，于是这间60平米的房子里就只剩下了她和孙子。孙子在附近的中学念初三，她知道他每天早上出门实际上是去安置区中心的广场边上和几个学生玩手机游戏，她说他，他不听，要打她，她后来就不说了。若不是她孙子有每个月三百块的国家补助，光靠她捡垃圾是养不活这个家的。

她拖着袋子从三号楼前的垃圾桶走向五号楼前，用搭在脖子上的黑乎乎的毛巾擦了一把汗。



#### 3.
还有个工人，移民搬迁到这里之前他就有一辆破旧的小卡车，他靠拉货为生。他有时候会接市区里的单子，把工厂加工好的成袋成袋的花生运到一个货运中心，有时候会跟着校长巡河，用他的卡车拖着大喇叭在安置区之间来回，更多的是接一些工地的活儿，运一些管道之类的建材。他已经攒了一笔不小的积蓄，加上政府分的房子，他想过段时间娶个老婆。他的卡车的空调是坏的，他在头顶装了一个小电风扇呼啦啦的吹，汗水就滴落在腿上。





## 关于血

#### 1.

她和妈妈还有弟弟在家，爸爸在浙江打工，初二。她是个普通的女孩儿，长相普通，学习成绩普通，家庭状况也普通，不活跃，也不是不说话，属于老师永远也注意不到的那种。中游成绩如她是考不上公立高中的，或许能考得上私立学校，但是考虑到私立学校一年八千块的学费，爸妈更愿意送她去读职校，学美容美发。

她最近很害怕，因为学校里面的一些传言。她听说上周，有个女孩儿死在学校里，被两个男的打死的。学校只完工了一部分，还有一部分是工地，但是因为资金问题停工了，学校怕孩子们被绊倒受伤，把工地的部分用围栏围起来了，她听说那个女孩儿就死在工地里。她不认识那个女孩儿，也没有见过，但是班长很笃定地说出了那个女孩儿的名字和班级，不像是撒谎。班长还说，上周警察来了，很多人都看到了。她又听班上的小混混说，如果不是保安大爷每天晚上放学后会巡查学校，女孩儿的尸体永远没人发现，他们说尸体被发现的时候已经死了很久了。至于为什么是被人打死的，而且是两个男人，那两个男人是谁，她就不知道了，所有人都说是听别人说的。学校依然照常上课，校长依然巡河，大喇叭的广播也不曾停下，保安大爷依然每天巡逻，正常得不能再正常，她甚至怀疑是不是真的有个女孩儿死了。她不知道，但是可以确定是，他们传言的那个女生确实没有再来过学校。



#### 2.
她的害怕不仅仅来自于那个或许被打死的女孩儿，更来自于一个曾经的同班同学，他犯事儿了，强奸罪，被抓去了十六中，也就是少管所。他坐在她后面，她很讨厌他，他经常上课从后面拽她头发，她就骂他，他咧咧嘴，往后一靠，双手抱在脑后，也不回嘴。上课时候他总在后面说话，也经常问她老师在讲什么，好不好玩，不过照例是不会听课的。


他最近不来上课了，你斜后方的和他玩得不错的差生说他进局子了，只知道是强奸，具体也不清楚。后来不知道从哪里传出来，说他在网上诱骗了一个初一的小妹妹，带回家里强奸了。她甚至可以想象得到14岁的少女的身体在他身下挣扎，处女血染红了床单，妖艳的红，红得她头晕目眩。后来又有人说，他是和另一个校外的男的轮奸的，还把那个女孩儿卖到别的地方去了，最后家长找到的时候，那个女孩儿已经神志不清了。她想到之前自己和他的矛盾，总害怕他跑出来报复她。

不过再后来，她一次因为上课睡觉，被语文老师叫到办公室用尺子打了手，然后罚站在办公室门口，老师们似乎忘了她，在办公室聊起了那个坐牢的男生。班主任说，他是被冤枉的，他说女方是个品行不端的学生，有时候在外面会做一些不好的事儿，他们最后上床了，男生有些用强，但是事后女生也没说什么，后来他们闹矛盾，女生跑去告了他强奸。她也不知道到底哪个版本才是真实的，但是她变得不太敢骂那些差生了。



#### 3.
她在QQ动态也看到过那令她头晕目眩的谣言的鲜红，是隔壁班的一个女生。女生把自己割腕的照片发在空间里，从手腕到大臂，女生的胳膊上布满了刀割的痕迹，有已经愈合的，有正在愈合的，还有新鲜的，流出令她恐惧的红色。她和女生不熟，她不敢问，她不知道女生为什么要这么做。学校查出来过一些学生有抑郁症，请来了一些大姐姐和他们聊天，没有那个女生。





## 关于欢笑

#### 1.

今年端午的包粽子大赛来的人格外多，或许是因为年初附近又新迁来了一批精准扶贫搬迁的人。如今这个安置区已经有近两万居民了。

从早上六点多，广场的吵闹声就把他从床上唤醒了，他从窗口往外看，广场上已经立起来了一个大牌子，上面写着花花绿绿的大字，但是他识字不多，看不太懂，不过从牌子上画着的粽子他能联想到，端午的包粽子比赛应该就在今天了。他之前在流水线上工作，但是上个月工厂设备换新，他下岗了，现在还没有找到工作。他知道，按照以往的规矩，凡是参与社区组织的包粽子比赛的，无论最后能不能拿奖，包的粽子都可以自己拿回家，他踩着拖鞋出门了。社区的大妈拿着喇叭，声音很大，翻了老半天终于在几十面的名单里找到了他的名字，然后给了他一个单子，让他签字，他不会写字，大妈拿来印泥让他按了手印。社区的人们陆陆续续围了一圈又围了一圈，混乱而嘈杂，鉴于居委会大妈的喇叭有些压不住了，比赛就这么提前开始了。裁判是附近中学的老师，他们在小桌子前面坐成一排玩手机。

排队入场，他拼了命地往前挤，别人也拼了命地往前挤，汗水从他黝黑的皮肤上转移到别人黝黑的皮肤上，没人在乎，堆起一张张笑盈盈的脸，眼前是一袋袋白花花的米，一摞摞绿油油的叶，一捆捆红艳艳的线。

粽叶薄得像纸，他费力地用擀面杖似的手指头绕着细细的线，洒落的米粒在木头桌子上蹦蹦跳跳，楼上的老田在围栏外面喊着什么，他没听清，但他知道不是什么好话，遂将毕生所学的脏字儿全都一股脑儿泼出去，广场上充斥着快活的空气。



#### 2.
今天初三老师的办公室里像过节似的，因为一袋子瓜子儿。在初三老师们的办公室里，瓜子儿是稀罕货，因为被超市里买的瓜子儿往往还没有到达办公室就会被校长收走。今天，年轻的实习老师就要离开了，他们拎着大包小包到学校来上最后一节课，一个知趣的小伙子拎了一袋子瓜子儿进来。

暂时不用管那个上课玩手机的孩子了，还有改了一半的语文作文，明天要做的扶贫调查以及这一周的家访，人民教师们围成一圈，男男女女老老少少，开始调侃刚哥的二宝，单身的老杨，梅姐女儿的男朋友以及田老师的秃头。瓜子壳儿劈里啪啦地落在桌子上，然后被扫进塑料袋，深深地埋进垃圾桶，再撕几页儿职校的宣传册盖好。

不能吃太久，因为晚上还有卷子要改，扶贫会议要开，建党周年的合唱要排练，剩下的瓜子儿收进抽屉里，等待着听下一轮欢笑。



#### 3.
来实习的大姐姐送了她一本字典，扉页写着祝福，她特别开心。她是初二班上的班长，成绩一般但是人缘很好。今天实习老师要和全班同学合影，她一直对着小镜子摆弄自己的头发。大姐姐温柔漂亮，身上香香的，自己却黑黑的矮矮的，她有些后悔以前为什么没有用妈妈的口红和粉底偷偷学一下化妆。

大姐姐是从海边来的，很远很远的地方，下课了就跟同学们聊大海，聊科技展，聊高中和大学，还有大鼻子的外国人。她想去大姐姐的家乡看看，在她的幻想中，那里有摩天大厦，那有JustinBieber一样帅的外国人，那里有大海，插着花儿的吸管和蓝色的鸡尾酒，有穿着吊带的美女，闪着七种颜色的彩灯，还有大学，教室的窗子都是落地玻璃……她低头看了看手里的一张便签纸，上面是她下课时候偷偷找大姐姐要到的QQ号，她把纸叠好握在手心，用另一只手捂着嘴笑。





## 关于泪水

#### 1.

班主任去他家里家访。小他两岁的妹妹还在正常上课，他已经有一阵子没有去上学了，每天晚上在家里通宵打王者荣耀，白天就睡觉。这是中午一点钟，班主任的敲门声把他唤醒，他去开门，班主任进来了，好像在说什么，他还没清醒过来，什么也没听进去。

他初三，还有十几天就要毕业了。他没有报名中考，他也不知道自己之后要做什么，能做什么，会做什么。他慢慢听懂了，班主任是过来劝他去读职校的，他低着头不说话。班主任说已经和他爸爸沟通过了，只要他自己愿意打一个电话给爸爸说他想读职校，他爸爸就给他读。班主任说他爸爸在广东打工这么辛苦就是为了他，他应该好好接着念书，学一技之长总好过直接进入社会。他眼泪往下滴，落在地板上。

“他管过我吗？”这是他说的第一句话。

“但是你爸爸要打工养你和你妹妹啊。”

“他给过我生活费吗？”这是他说的第二句话。

“你爸爸不给你生活费吗？”

他点头，眼泪滴下来。

班主任不说话了。

“那你生活费怎么来？“

“妹妹。“这是他说的第三句话。

然后就是更长久的缄默。班主任知道他父母离异了，他判给了父亲，妹妹判给了母亲，法院上他们说各自给自己负责的孩子生活费。

班主任长叹一口气。



#### 2.
男孩儿转校了，昨晚离开的，说是被家里人带到外省去了，真假细节没人知道。男孩儿是女孩儿的同桌，女孩儿没有爸爸妈妈，家里只有一个老奶奶。老奶奶打扫家里的卫生，给女孩儿做饭，但是听不懂女孩儿的敏感。女孩儿只好跟男孩儿说，说她的开心与难过，她的悔恨与憧憬，她的惊喜，她的失落，还有，她的依赖，她的懵懂。男孩儿成了唯一一个听这个内向的女孩儿说话的人，成了她生活中最重要的人，直到，他的消失。

这片土地上有山雨和雾气，女孩儿站在雨中，不知道要去哪，不知道要干嘛，她不想回到那个身畔只有一张空桌子的座位，雨水划过她的脸颊，或许混着泪。班长来了，班主任来了，校长来了。校长没打伞，陪着女孩儿淋雨，他说男孩儿去重庆了，他又说十几岁的小孩哪里懂恋爱，他说女孩儿可怜。然后班长走了，班主任走了，校长走了。

女孩儿还站在雨里。



#### 3.
她今年14岁，站在学校走廊，要跳楼。她看着下面广场上的同学们，下面的同学们看着她，她有些腿软，又不太敢跳。

她被查出来抑郁症，重度。她不说话，没有朋友。有人说，她之前失踪是因为被抓走了，有人说她被抓走以后被逼卖淫了，除了她自己没有人知道真假，或许校方知道，她不说，校方不说。

她身后尽是喧嚣，好像有男人的奔跑声和喘息声。她感觉自己的脚底离开了地砖，等回过神，她被班主任抓住胳膊拎着。班主任浑身是汗，把她的手腕捏得生疼，她满眼是泪。





## 关于烟尘

#### 1.

十年前，这片土地上长满了一人高的草，除了每年清明去对面山上扫墓的农人会挎着镰刀走过这里，就只剩虫鸣与鸟叫了。

后来，开来了挖土机，渣土车，荒草连带着下方的泥土一起被掀起，石砾筑起路基，滚滚烟尘被车轮履带卷起。

浓烟，轰鸣，鲜红的标语，雪白的灯光，还有耀眼的电焊和滚烫的沥青，一片片钢筋水泥的丛林拔地而起。密密麻麻的窗口，像蜂房，每一扇窗里都亮着一盏灯，每一盏灯下都藏着一个故事。他们来自不同的山野，他们讲述着同样的故事。房子里有厨房和卫生间，厨房有煤气，卫生间有马桶，有人会用，有人要学，房子里有客厅，客厅的墙上有习主席的画像和精准扶贫的字样，有人看不懂字，但大家都知道什么意思。

如这样的安置区一共有三片，加起来近四万居民，附近还有三所幼儿园，两所小学和一所中学，学校的营养餐是补贴的，学生不用花钱。

人们已经不知道这里曾经是什么样子了，只有附近的农户知道这片土地下埋葬着虫鸣、鸟叫、生锈的镰刀；农户也不知道以前的山村是什么样子，只有这里的居民知道大山深处埋葬着贫穷、苦痛、夭折的孩子。





## 关于星光

#### 1.

今夜难得没有云，星空格外璀璨。

他和那些来实习的大学生不一样，虽然年龄差不多，但是他是这个中学的正式的老师，白净，斯文，带着无框眼镜。

他刚来到这里一年，本地的方言还说得不是非常利索。他还没谈过恋爱，喜欢天文，历史，喜欢旅游，喜欢孩子。最近来这里的实习老师办了很多本地没有的讲座，他跑去坐在学生的位置，认认真真地听了好多节课。

他躺在车顶，双手交叉枕在脑后，看着夜空出神。夏季银河横亘在星空，贯穿南北，他看着，想到了今天下午讲座里实习老师讲的托勒密、第谷还有伽利略。那些实习老师应该快走了罢，他们就要回到他们自己原本的轨迹去，读研或是去北上广工作。自己呢？应该就在这里当一辈子老师吧，就这样结婚生子，拿着微薄的工资，然后逐渐老去，白净的皮肤被晒得黝黑，挺拔的脊梁逐渐佝偻……他想到了校长，校长似乎也是这样，才四十多岁看起来却像六十多一样，那辆桑塔纳的玻璃都裂缝了也没有修。



#### 2.
看着同一片星空的，还有一个女孩儿。女孩儿15岁，初三，马上就要中考了。她在班里是尖子，但是也不知道自己能不能考上高中。私立高中应该是没问题的，但是太贵了，职校也没问题，但是妈妈不让他去，说亲戚的孩子在职校三年啥也没学到，所以不如早点工作挣钱。实习老师说她只要努力就可以上高中，她将信将疑，但是心里很开心。她最最憧憬的地方是大学，上了大学，她就可以住进城市里，认识全国各地的朋友，然后研究高深的学问，找一份体面的工作。实习老师说大专的分数很低，她是不太信的，毕竟在她们这里，对于大多数学生来说，高中都是奢望。

天上划过一颗流星，她幻想着有一天能踏进大学的校门。来实习的大学生没有忍心告诉她的是，在那边，大学生如同流水线一般被加工出来，人人都是大学生，然后毕业，失业。



#### 3.
他弹了一下烟灰，也看着夜空。他是学校的老油条了，迁来这里之前留了两年级，校长也拿他没办法，特批他上课可以不在班级里听课，代价是他白天要来学校，不能去外面混。烟的名字叫磨砂，本地品牌，在佛山的老爸每个月给他的生活费不少，够他每天一包十块钱的磨砂香烟。来实习的大学生们要走了，他没什么感觉，从这个中学建校就转学到了这里，这种人他见得多了，不尊重，不羡慕，也不去打扰他们。他看着星空，却想到了小杨老师。小杨老师是他在这个学校的第二年遇到的，来这里支教了半年，很不幸的遇到了他们混子班。小杨老师是个女孩，文静可爱，他一开始总捉弄她，抓虫子放到她包里听她尖叫。他对她吹口哨，吐烟圈，当着她的面翻墙溜出学校，小杨老师被气得蹲在地上哭。后来，他却逐渐喜欢上了这个可爱的支教老师，他依然不上课，却不再捉弄她了。他自己也分不清自己对小杨老师是什么情感，也不想深究。小杨老师早就离开了，走的时候给他们班上每个人发了一个本子，扉页写了一些她想对那个学生说的话，他拿到的那个本子上只有短短的一行祝福——小杨老师根本不了解他。但是这个本子他一直珍藏着。


## 关于夜

#### 1.

他晚上照例是不睡觉的，刷一晚上短视频或者打一晚上游戏，他都早已习惯了。他已经辍学一年了，按照年龄来说他今年应该高一。他晚上不睡觉是因为他妈妈晚上也不睡觉。他家里只有他和妈妈，妈妈很有经济头脑，把家里改造了一番又跟隔壁的大叔不知道怎么谈的，把那一户也占下来了，然后妈妈买了四台麻将机，周围的邻居闲下来就到他家里来赌钱。他家里大半的生活费就从这四台麻将机上得来。这四台麻将机几乎是24小时不停运转的，他妈妈晚上陪他们打牌，白天就在屋里睡觉，他也是白天睡觉，不过在一个小摊位上睡觉，顺便卖一些假烟和假酒补贴家用。

班主任时常来“做工作”，就是说服他妈妈让他去读职校，但是妈妈一直不松口。他妈妈说，他平时在学校成绩就垫底，不是学习的这块料，即使去了职校还是什么都学不到，还要交学费，反而不如早点工作赚钱补贴家用。他其实几个月前去了一趟深圳，去打工，但是两个月后就回来了，太苦，他受不了。



#### 2.
她初一的时候曾经是那个女孩儿的好闺蜜。女孩儿个子不高，但是很漂亮——大眼睛，有点婴儿肥的脸蛋，一头长发总扎成一个马尾。女孩儿的性格也好，文静，不怎么活泼但是很友善，所以大家也都很喜欢女孩儿。初一的时候她是女孩儿的同桌，知道班上有不少男同学都对女孩儿表过白，女孩儿说他们幼稚，都拒绝了。

女孩儿知道自己长得漂亮，也喜欢打扮，但是学校不允许女学生化妆，所以女孩儿也只是放学回家以后会对着镜子臭臭美。再后来周围的同学都开始玩短视频软件，女孩儿也开始玩，并且自己开始拍一些生活的片段，班上的很多同学都关注了女孩儿。女孩儿很开心，开始从其他的短视频里面学习穿搭，学习妆容，缓慢地积累着自己的粉丝。

之后呢，具体的细节她就不清楚了，只知道是女孩儿的短视频账号收到了很多私信，之后她回复，然后就是聊天，然后成为朋友，然后线下见面，然后潘多拉的魔盒就打开了。女孩儿和他们接触了很长时间，期间具体的情况她太了解，只知道后来女孩儿就不怎么来上学，直至最后就彻底消失了。学校去找过，去联系过女孩儿在外打工的家长，女孩儿的家长回来了，人还是没找到，于是，在派出所的记录里女孩儿的名字后面被加上了一条记录——“失踪”。

实际上女孩儿没有失踪，班上有几个男生反而不知道为什么能联系上公安局都找不到的女孩儿，他们说，女孩儿先是去了市里面的KTV工作，后来又到某个洗浴中心，身价很不便宜。她最早听到这个消息的时候是不太相信的，直到后来初二的时候在安置区的广场碰到了这分别一年的好闺蜜。她没认出女孩儿，是女孩儿先认出来她的，因为女孩儿的变化太大了。酒红色的披肩的卷发，金闪闪的圆形的耳环，深邃的眼影，粘腻的睫毛膏，不大的胸部被很刻意地裸露着，她在这个人的身上完全找不到曾经的女孩儿的影子了。女孩儿开心的笑容显得真诚而感慨，问她这一年来过得怎么样，毕业以后什么打算，她很局促，女孩儿问一句她答一句，像在老师办公室里一样。她说她估计考不上高中了，家长也不想让她去职校，她也不知道以后能做什么。女孩儿靠得离她近了些，一股香水味往她鼻子里钻，女孩儿劝她以后如果没有出路不如加入女孩儿她们，工作轻松，赚的钱多。女孩儿说自己一年前一个月的生活费只有几百块钱，现在一晚上就能赚到上千，女孩儿还说要送她一只口红。她有些害怕，低着头没敢看女孩儿，只盯着女孩儿华丽的指甲盖儿，她能听出女孩儿语气里的真诚，对自己的害怕又感到些许愧疚。她现在明白了为什么女孩儿失踪以后女孩儿家长没有到处寻人，学校也悄悄地把女孩儿的名字从名单里删掉了，他们或许是放弃了，或许是默许了。

她自己也不知道该怎么面对女孩儿了。



## 关于沉默

#### 1.

她今年初三了，即将面临中考。她本是班上名列前茅的优等生，有很大的机会升学进入高中，但是最近成绩下滑得很严重。班主任觉得她不对劲，去家访，去找她谈话，她说什么事也没有，自己会努力的。

她其实有事儿，但是她不说。她谈了一个男朋友，社会上的，发生关系了，怀孕了，借钱了，打胎了，钱还不上了。她上周有一天没有来，没人知道去哪了，她不说。她男朋友似乎还逼迫她做过一些其他的事情，具体不知道。或许她早就想逃离魔爪，但她不知道该怎么做，或许她仍钟情于男子不愿脱身，甘愿一次次伤害自己，没人知道到底是怎么回事，因为她不说。其实这个传言也不知道是从哪里来的，她从来不回应这些，她只是沉默，什么也不说。



#### 2.
学校其实还没有完工。

在规划里，学校很大，有跑道和足球场，行政楼和教室，还有实验室和机房。但是现在，学校只有教室和食堂，勉强供学生上课，老师们的办公室是教室改的，机房有了，但是没电脑。移民搬迁的学生们住的安置区和学校之间隔了一座土山，不矮，规划里有马路连接起来。实际上这条路也有了雏形，砂石的路基已经完工了，只是缺了柏油没有铺上。

但是现在，在这片土地上已经看不到工程队了，所有的项目都停工了。学校盖了一半，校长只好把工地的部分用铁丝网围起来等待其完工，但是铁丝网破了又补补了又破。而已经修建了路基的马路呢，因为停工时间太长，凹陷积了水，水边又长了草，学生上学就从这草里过，又在这本该是柏油路的地方踩出一条泥巴路。

校长说，这附近的安置区和学校都是国家精准扶贫安排的，校长又说，现在资金不够，所以这些工程都停工了。

为什么资金不够了呢？没人知道。

毕竟这片土地也不会说话。



#### 3.
出租车司机说，现在物质生活丰富了，治安也好了，是的，市里面的一切都欣欣向荣。司机师傅已经五十多岁了，在这里住了大半辈子，但是他也不知道在这个城市的市郊还藏着一片安置区，有几万人，有老人，有孩子，有血，有汗，有欢笑，有眼泪，有烟尘，有星光，有不眠之夜，有无数的隐秘。

他们安静地住在这里，如同这些隐秘一样，一言不发，除了他们自己以外，没人知道。





#### 4.
我也不敢说我真正接触到了这些秘辛，我只是一个过客，什么也带不来，什么也带不走。我只能尽可能真实的记录我的所见所闻，然后悄悄的在你们耳畔诉说。

我迫切的想打破沉默。

但我又不敢喧哗，害怕打破这片土地的沉默。