---
title: '2022年终找补'
author: "Midstream"
date: '2022-12-27'
categories: ['日常']
description: 我不怎么拍照片，这是个坏习惯，我也不写日记，这也是个坏习惯，我只能暂且在这里找补了。

---

2022年过去了。一直到我准备写下这些文字的时候，我才发现原来不只是2022年，还有更之前的两年，竟然没能留下些许供我缅怀的凭借。原来，年终总结也这样步步紧逼，不给人喘息的机会，上一次才刚刚结束下一次已经迫在眉睫，稍有不慎就会错过。像上班打卡，像写日记。一年的时间在丢失的时候，感觉比一天还轻。

于我而言，年末的总结更像咽拭子，用一根签捅进回忆里生硬地搅拌，检测核酸一样检测生活，让人想干呕。检测结果们整整齐齐排列起来，没人会去看，但每次都不容遗漏，否则就丢失了那一年的行踪，要面临日后的追责。每当完成年终的总结，便觉得守住了这一年的日子，未来不会患得患失。这让人有一种24小时核酸阴性的安全感，只觉得可以放心走进明天了。

不过，核酸检测大约在20天前就逐渐取消了，让人觉得恍然。

我不怎么拍照片，这是个坏习惯，我也不写日记，这也是个坏习惯，我只能暂且在这里找补了。

## CC

CC的全名应该叫做会议中心？叫什么不重要，我在这里一间房号为4005的屋子渡过了好些个月份。这栋楼房在校园里，上课和吃饭比较方便。那个时候我性格也和现在不太一样，进入过学校的各种厅堂，在里面看到了很多朝气蓬勃的同龄人。

我有交往一些朋友，其中不少住也住在CC，相互之间往来也很积极。那时的我对“校园生活”这个话题应该有很多话可说。

也是从那一年开始，我搭建了我的博客，文字鲜活。

## 和风雅颂之一

和风雅颂是我学校的学生公寓所在的地方。几经波折，我有幸在一间较大的套间里居住了一阵。

应该是有一段时间，我相当痴迷于生活本身，我不知道那段日子的色调是否是那个小小的厨房带给我的。后来，因为私自打开煤气阀门，我被学校秋后算账了。

房间里有客厅，客厅有地毯，有懒人沙发，有扑克牌，也同样是个朋友聚会的好去处。

在和风雅颂周边相当近的地方，有后来彻底吃腻的麦当劳，有一个相当大的森林公园，有一个健身房，有不少住宅区。也有段时间晚上经常出门散步，有时一走能走数个小时，绕到很远的地方。

同样在和风雅颂不远的地方，有一个“西城后街”，街不大，有饭店咖啡馆和书店，曾常去看书。

## 和风雅颂之二

上述的那些有的或许是2022年的，有的或许是更早的时间的记忆了，几百个日日夜夜在我脑袋里糊成一团。

我能确定的，2022年的记忆，从三月份开始。

进出宿舍楼不再像之前那样方便了。室友并不在，于是有那么一阵日子，我的窗帘从未拉开过，困了就睡，醒了也不知今世何时。口粮是学校外送的盒饭。

好在有一个电脑。当时打的游戏是《怪物猎人：世界》，这个游戏前后消磨了我几百个小时，最终boss黑龙也打进了10分台（即11分钟内通关）。

这段时间借了朋友的吉他开始乱弹琴，我的头发也是在这段时间里变长了。

## 家

我也记不清是什么时候解封了。只记得暑假是回到了家。在家的日子很惬意，于是就记不清细节，只觉得几个月一晃就过去。

只记得当时开始听椅子乐团的歌，翻译了《long distance》。

## 安亭新镇

新镇是个相当好的地方。新镇的确自成一个小镇，被一条环形公路包围起来，仅有一条干道横穿这个圆形的区域与外界连接，于是这个镇子也就只有两个出入口。镇子内的人若不乘坐汽车是很难去往外界的，进出的公路两侧有很漫长的荒芜，这或许也正是新镇的可爱之处——像一个小小的岛屿，岛民们说话的方式和身上的味道都和几公里外的岸上不同。

环形公路内部，新镇被几条小路井字形分割，仅有一处商业区和数个住宅区，路边的房子多尖顶，房顶为红黄蓝这般鲜艳的色彩。

新镇不新，但是它曾经必定有“新”的时候，中心的广场的建筑风格昭示着，在新镇尚新的时候定然不安于成为一个静谧的小岛。不过现在那些野心勃勃的办公楼里多空荡，广场上每天都有非常多的老人和孩子，他们每日在广场拉家常或是嬉闹，撑起了商业区的繁华。

新镇很小，节奏很慢，绕着新镇的“环岛路”走一周只需要不到两小时，傍晚出发，等到回到原地的时候天就已经黑下来，新镇里就听不到什么声音了。家家户户的灯光这时会亮起来，因为新镇没有高楼，所以散步时能轻易看到各户内灯光映出的光景，多是孩子和书桌，背景的墙面花花绿绿，有的挂着彩带。

新镇同时也是一个相当枯燥的地方，或许是因为我住在新镇的日子较为舒心，没有我自己的期末焦虑，也没有周围的人心惶惶，只是上班下班，还有就是在新镇散步，因此我新镇的枯燥反而让我感到闲适。

总而言之，新镇离上海很远。

## 繁兴路

我是2022年国庆节从新镇搬至繁兴路的。

繁兴路很短，短到它仅有的两个路口都是丁字口——一个是头，一个是尾。但就这样一条小小的路，总是塞满了各式各样的人和车，脏乱而喧嚣，上下班的时候更是水泄不通。繁兴路上黑色的柏油比别的路都更黑，带着油腻的光泽。

繁兴路的两端各有一个核酸亭，每晚下班时间的队可以排半条路的长度。

繁兴路周边是极其喧嚣的，喧嚣到让人觉得焦躁，几家营业到凌晨两点的炸鸡店和臭豆腐店还有烧烤摊是我唯一留恋的地方。当忙碌于做不完的任务和项目至凌晨，一份酥脆的炸鸡可以让人再撑两个小时。

另外值得一说的就是，在靠近年末的时候，繁兴路的核酸队伍排得越发长了。公寓的人们也逐渐习惯了时常坐在楼下的大爷——他的职责是避免住户离开这栋公寓。

或许是生活越艰难想说的话就越多，也或许是现实越惨淡就越想逃避，纵使我在繁兴路一直焦头烂额，却产出了许多博客，捏造了很多小故事。

我也不好说繁兴路究竟是怎样，或许只是我去的不是时候。

<br></br>

我不怎么拍照片，这是个坏习惯，我也不写日记，这也是个坏习惯。过去的三年里我变了很多很多，可是我却说不出来我经历了什么。我在大背景里随波逐流，经历的一切都那么独特，但又那么普通。

虽然我说不出什么，但是这三年已经在我身上留下了痕迹。人所做过的一切都会在身上留下印记的——我膝盖上的伤疤，手指上握笔产生的鼓包，腿上生长纹褪去后留下的纹理……我不知道这三年给我留下了什么，但我确信，会有一些我将背负终身的印记来自这些时光。

时光还将继续雕刻我，这也不是坏事。

祝我自己新年快乐吧。