---
title: '员工之二'
author: "Midstream"
date: '2023-06-11'
categories: ['小说']
description: 施放啊施放！你是施放，你怎么落魄到住进木桶！你是施放，你怎么豁达到住进木桶！

---

我也未曾想过，《员工》一文会有续集，所以《员工》为《员工》而非《员工之一》。

但是施放丢了，他就那样离奇地消失在了入职前一天的夜里。

我去寻找施放的下落。



## 1

施放曾经踏上过的路再被我踏上

从煤气公司出发

前往微普通的九十九道高墙

我知道

他的背影最后一次出现在一个男人的瞳孔

那晚他们被困在夜色的小牢笼里



我翻过九十九道墙

看到摩天的塔

我在一个螺丝钉的孔洞里找到了男人

男人满眼彷徨

他在螺丝钉的洞里往地下挖掘

地震要来了，我听见男人说

高塔会变成废墟，城墙会成为遗迹

只有地下的宫殿才能幸免

可是地下不应该更危险吗？

男人摇头

那里是地震的来源，也是台风的眼

我看向男人挖掘的隧道

你真的能到达晴朗的风眼？

男人不知道

那就远航吧，我劝男人

等地震过去

你一定要乘着你的独木舟归来

男人邀请我一同远去

可我还要寻找施放

男人说

天台那晚，施放走向大山的方向



## 2

施放曾经踏上过的路再被我踏上

大山是施放的家乡

他在这里休憩

也在这里堕入迷惘

山民不再用炙烤的豚设宴

施放已沦为魍魉

山民说，他骗走了我的儿子和猪

他逃难般归来，被逐之而去以棍棒

山民的儿子带走了自己和施放留下的钥匙扣

那上面有微普通的徽章



他在为自己的儿子哭泣

更为了作物和牲畜

今年不是丰收年

唯一的种猪也特立独行

它长满黑色鬣毛的身体发硬发僵

胯下的长鞭却逐渐枯萎

它粗壮的颈动脉被利刃切开

人们却发现它的排骨硬得无法入口

我给予山民真挚的祝福

别舍弃你的猪肋，别泯灭了你的希望！

你的儿子会归来

带来财富和丰收

会有沃土

会有软肋



## 3

施放曾经踏上过的路再被我踏上

山民说施放逃往边疆

那里有奇险的山路和豺狼

也有遍地黄金的传说和神话

市集里聚满巨富商贾和走投无路者

一朝万劫不复，一朝腾达飞黄

施放啊

你千万别在这里堵上你的性命



穿着袍子的人拉住我

是骗子或是巫医

我用珍贵的泉水

找他换取施放的消息

他桀桀地笑

你说的人早已离开这里

他输的一塌糊涂

已经回到镇里贩卖煤气

可是他又如何能回到公司呢

哪怕他曾经是上进的员工

他为了微普通葬送了前程

他的档案有抹不去的污点

更何况

微普通都大厦将倾

哪还有公司愿意接纳施放

匆匆的旅人啊

我一直追不上施放的步伐

感谢您的慷慨！

我听到骗子或是巫医的声音



## 4

施放曾经踏上过的路再被我踏上

穿过沙漠

我回到镇子上

存在镇的人们聚集在大街

大家在讨论一种慢性病

或许也不是病

而是身体的自我保护



你会变得迷茫

他们说

然后会变得疯狂

你奔跑，你追逐

你总趔趄

你像走肉行尸

你慢慢的走不动了

你坐下来歇息

你任由他人奚落

你任由坐吃山空

然后

你感觉到大地的抚慰

你想成为一棵树

把腿扎根到湿润的泥土里

倚靠着青山发呆

于是你真的往树的方向进化

你的脚趾甲显现出木头的质感和色泽

木头向着里也向着外生长

你的下肢都变成了木头

木头逐渐弯曲形变

又变成一片片木板，把你包围

你想变成一棵树

却变成了一个桶



## 5

施放曾经踏上过的路再被我踏上

穿街走巷

我在镇里寻找施放的痕迹

我遇到一位在垃圾桶里翻找食物的年轻人

于是我用一顿午餐换取施放的消息



你说的人我认识

我多么希望他还在这里住居

他舍弃许多腐烂的蔬菜

没有他我甚至无法继续拾荒

他每日买进新鲜的蔬菜

再把蔬菜放进冰箱

除了蔬菜还有鸡蛋牛奶和猪肋

只有丰满的食材才能压制他的惊慌

可是他不会烹饪

只能任由冰箱里的食物慢慢腐烂

他会补充新的

欺骗自己生活于正常

我感到荒谬

可是他为什么要这样？

拾荒者说

他不仅购入食材

每日也有必须的行程

他会带上他的电脑

日日去咖啡馆里端坐

那里是公司员工的聚集地

他自费过着公司员工的生活

如今他已经离开

没人知道去了哪里

这就是我知道的全部

如果可以

我希望您能继续

资助我一顿晚宴



## 6

施放曾经踏上过的路再被我踏上

匆匆的旅人啊

我在存在镇流浪

大风吹过

我看到一只木桶

木桶骨碌碌的滚动

里面住着一个人

他手拿一柄锤子

控制着方向

人们说

他是住在木桶里的放浪形骸者

他看透了人生

抛却功名利禄

人们又说

他是得了怪病的失败者

想要成为一棵树

却变成了一个桶

人们还说

他是不知廉耻的疯癫者

他衣不蔽体

在木桶里旁若无人地手淫



可是我认识他

施放！

我凯旋高歌

施放啊施放！

你是施放，你怎么落魄到住进木桶！

你是施放，你怎么豁达到住进木桶！

我看到施放充满泪水的眼眶

还有他嘴角痴愚的傻笑

他的双腿已经化作木质

成为了他居住的木桶了

施放啊施放

你也曾是一名上进的员工

你也曾拥有自己的梦



可是

或许木桶本就是你最好的归宿

虽然没有帝王亚历山大向你躬身

也没有信徒向你谄媚



## 7

施放曾经踏上过的路再被我踏上

我彷徨着不知去向

施放曾经踏上过的路再被我踏上